spring:
  cloud:
    stream:
      bindings:
        aggregateWeather-in-0:
          destination: weather-data
        aggregateWeather-out-0:
          destination: app-weather-data
        alternativeProcessor-in-0:
          destination: app-weather-data
        alternativeProcessor-out-0:
          destination: weather-alarms
      kafka:
        streams:
          binder:
            configuration:
              default:
                timestamp:
                  extractor: com.example.streams.WeatherDateTimeExtractor
            functions:
              aggregateWeather:
                applicationId: aggregateWeather-0.0.1
              alarmProcessor:
                applicationId: alarmProcessor-0.0.2
#      function:
#        definitions: aggregateWeather;alarmProcessor;
spring.cloud.stream:
  function:
    definition: aggregateWeather;alarmProcessor;

logging:
  level:
    org:
      apache:
        kafka:
          streams: info
    com:
      example:
        streams=INFO: